### ISSUE TITLE
Bug: "fzg.writeSync" is not a function

### ISSUE THREAD

**Issue by Befrog57** [Befrog57/divera-alarmlicht#13]
Node should just add the correct string in front of "writeSync" and not assume that the var-name is "fzg"

Error log:
```
/home/pi/JavaScript/git/divera-alarmlicht/alarmlicht.js:85
  fzg.writeSync(0);
      ^

TypeError: fzg.writeSync is not a function
    at setPin (/home/pi/JavaScript/git/divera-alarmlicht/alarmlicht.js:85:7)
    at /home/pi/JavaScript/git/divera-alarmlicht/alarmlicht.js:63:9
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

**Comment by Befrog57** [comment]
Fixed in #14
